from __future__ import annotations

from core.diagnostics.models import DiagnosticAction, DiagnosticCase, DiagnosticCheck


def _a(action_id: str, prio: int, de: str, en: str) -> DiagnosticAction:
    return DiagnosticAction(id=action_id, priority=prio, text_de=de, text_en=en)


def _c(check_id: str, desc: str, expects: str) -> DiagnosticCheck:
    return DiagnosticCheck(id=check_id, description=desc, expects=expects)


DIAGNOSTIC_CATALOG: list[DiagnosticCase] = [
    DiagnosticCase(
        id="BACKUP-MANIFEST-001",
        domain="backup_restore",
        title_de="Manifest fehlt im Backup",
        title_en="Manifest missing in backup",
        summary_de="Das Archiv ist ohne MANIFEST.json nicht als belastbares Restore-Backup nutzbar.",
        summary_en="Archive without MANIFEST.json is not reliable for restore validation.",
        severity="critical",
        confidence="high",
        detection_sources=["api_result", "file_check"],
        checks=[_c("manifest-present", "Pruefe MANIFEST.json im Archiv", "present")],
        root_causes=["Unvollstaendiger Backup-Lauf", "Archiv manuell veraendert"],
        recommended_actions=[_a("recreate-backup", 1, "Backup neu erstellen und Verify ausfuehren.", "Create a new backup and run verify.")],
        related_docs=["docs/developer/BACKUP_MANIFEST.md"],
        related_faq=["docs/faq/RESCUE_FAQ.md"],
        tags=["manifest", "fail-fast"],
    ),
    DiagnosticCase(id="BACKUP-ARCHIVE-002", domain="backup_restore", title_de="Archiv beschaedigt", title_en="Archive is corrupted", summary_de="Gzip/Tar-Integritaet fehlgeschlagen.", summary_en="Gzip/tar integrity failed.", severity="critical", confidence="high", detection_sources=["api_result"], root_causes=["Abbruch beim Schreiben", "Speichermediumfehler"], recommended_actions=[_a("use-other-archive", 1, "Anderes Archiv pruefen.", "Verify a different archive.")], tags=["archive", "verify"]),
    DiagnosticCase(id="BACKUP-HASH-003", domain="backup_restore", title_de="Hash-Mismatch", title_en="Hash mismatch", summary_de="Manifest und extrahierte Daten stimmen nicht ueberein.", summary_en="Manifest hash and extracted data do not match.", severity="high", confidence="high", detection_sources=["api_result"], root_causes=["Dateibeschaedigung", "Falsches Archiv"], recommended_actions=[_a("new-backup", 1, "Neues Vollbackup erstellen.", "Create a new full backup.")], tags=["hash_mismatch"]),
    DiagnosticCase(id="RESTORE-PATH-004", domain="backup_restore", title_de="Unsicherer Restore-Pfad", title_en="Unsafe restore path", summary_de="Path-Containment wurde verletzt oder Pfad ist nicht erlaubt.", summary_en="Path containment failed or path is not allowlisted.", severity="critical", confidence="high", detection_sources=["api_result", "file_check"], destructive_risk=True, requires_confirmation=True, tags=["path_containment"]),
    DiagnosticCase(id="RESTORE-PARTIAL-005", domain="backup_restore", title_de="Restore nur teilweise erfolgreich", title_en="Restore partially successful", summary_de="Kritische Dateien fehlen nach Restore.", summary_en="Critical files are missing after restore.", severity="high", confidence="high", detection_sources=["api_result"], tags=["partial_restore"]),
    DiagnosticCase(id="RESTORE-RUNTIME-006", domain="app_setuphelfer_runtime", title_de="Restore ok, Dienst startet nicht", title_en="Restore ok, service does not start", summary_de="Daten sind zurueckgespielt, Runtime ist aber nicht betriebsbereit.", summary_en="Data restored but runtime is not operational.", severity="high", confidence="medium", detection_sources=["systemctl", "api_result"], tags=["post_restore", "systemd"]),
    DiagnosticCase(id="RESTORE-TMPFS-007", domain="storage_filesystem", title_de="Restore in /tmp fehlgeschlagen", title_en="Restore on /tmp failed", summary_de="/tmp (tmpfs) reicht fuer grosse Restore-Daten oft nicht aus.", summary_en="/tmp (tmpfs) often lacks space for larger restores.", severity="medium", confidence="high", detection_sources=["file_check"], tags=["tmpfs", "storage"]),
    DiagnosticCase(id="PERM-GROUP-008", domain="permissions", title_de="Gruppenmodell fehlt", title_en="Group permission model missing", summary_de="setuphelfer-Gruppe/0770/SupplementaryGroups ist nicht konsistent.", summary_en="setuphelfer group/0770/SupplementaryGroups is inconsistent.", severity="high", confidence="high", detection_sources=["config_check", "file_check"], tags=["permissions"]),
    DiagnosticCase(id="SYSTEMD-START-009", domain="systemd_services", title_de="Dienst startet nicht", title_en="Service fails to start", summary_de="systemd meldet Startfehler.", summary_en="systemd reports startup failure.", severity="high", confidence="medium", detection_sources=["systemctl", "log_pattern"], tags=["systemd"]),
    DiagnosticCase(id="SYSTEMD-CRASH-010", domain="systemd_services", title_de="Dienst startet und crasht", title_en="Service starts then crashes", summary_de="Dienst faellt nach kurzer Laufzeit aus.", summary_en="Service exits shortly after startup.", severity="high", confidence="medium", detection_sources=["systemctl", "log_pattern"], tags=["crashloop"]),
    DiagnosticCase(id="RUNTIME-PORT-011", domain="app_setuphelfer_runtime", title_de="Port nicht gebunden", title_en="Required port not bound", summary_de="Backend/UI-Port ist nicht offen oder belegt.", summary_en="Backend/UI port is not open or is already used.", severity="high", confidence="high", detection_sources=["api_result", "log_pattern"], tags=["port"]),
    DiagnosticCase(id="NODE-OPTIONS-012", domain="app_setuphelfer_runtime", title_de="NODE_OPTIONS fehlen", title_en="NODE_OPTIONS missing", summary_de="Runtime-Umgebung fehlt notwendige Node-Optionen.", summary_en="Runtime environment is missing required Node options.", severity="medium", confidence="medium", detection_sources=["config_check", "systemctl"], tags=["node"]),
    DiagnosticCase(id="SYSTEMD-RESTRICT-013", domain="systemd_services", title_de="Restriktive Unit blockiert Laufzeit", title_en="Restrictive unit blocks runtime", summary_de="Unit-Optionen verhindern benoetigte Zugriffe.", summary_en="Unit options block required runtime access.", severity="high", confidence="medium", detection_sources=["systemctl", "config_check"], tags=["unit-hardening"]),
    DiagnosticCase(id="SYSTEMD-AF-014", domain="systemd_services", title_de="AddressFamily zu restriktiv", title_en="AddressFamily too restrictive", summary_de="Netzwerkfamilien sind in der Unit nicht freigegeben.", summary_en="Required address families are blocked by unit settings.", severity="high", confidence="medium", detection_sources=["systemctl", "config_check"], tags=["addressfamily"]),
    DiagnosticCase(id="UI-NO-BACKEND-015", domain="app_setuphelfer_runtime", title_de="UI erreichbar, Backend nicht", title_en="UI reachable, backend not", summary_de="Frontend laeuft, API-Dienst ist nicht erreichbar.", summary_en="Frontend is running but API service is unreachable.", severity="high", confidence="high", detection_sources=["api_result", "systemctl"], tags=["frontend", "backend"]),
    DiagnosticCase(id="SSH-PORT-016", domain="ssh_remote_access", title_de="SSH-Port geschlossen", title_en="SSH port closed", summary_de="Port 22 antwortet nicht.", summary_en="Port 22 is not reachable.", severity="medium", confidence="high", detection_sources=["network", "config_check"], tags=["ssh"]),
    DiagnosticCase(id="SSH-DISABLED-017", domain="ssh_remote_access", title_de="SSH deaktiviert", title_en="SSH disabled", summary_de="SSH-Service ist nicht aktiviert.", summary_en="SSH service is disabled.", severity="medium", confidence="high", detection_sources=["systemctl", "config_check"], tags=["ssh"]),
    DiagnosticCase(id="DNS-018", domain="network", title_de="DNS-Aufloesung fehlerhaft", title_en="DNS resolution failing", summary_de="Namen koennen nicht in IPs aufgeloest werden.", summary_en="Hostnames cannot be resolved to IP addresses.", severity="medium", confidence="medium", detection_sources=["network", "api_result"], tags=["dns"]),
    DiagnosticCase(id="NET-IFACE-019", domain="network", title_de="Falsches Interface/IP", title_en="Wrong interface or IP", summary_de="Verbindungsversuch nutzt falsche Ziel-IP oder falsches Interface.", summary_en="Connection target uses wrong IP or wrong network interface.", severity="medium", confidence="medium", detection_sources=["network", "api_result"], tags=["ip"]),
    DiagnosticCase(id="FIREWALL-020", domain="security_hardening", title_de="Firewall blockiert Zugriff", title_en="Firewall blocks access", summary_de="Regeln blockieren benoetigte Verbindungen.", summary_en="Firewall rules block required traffic.", severity="high", confidence="medium", detection_sources=["config_check", "api_result"], tags=["firewall"]),
    DiagnosticCase(id="FS-RO-021", domain="storage_filesystem", title_de="Dateisystem read-only", title_en="Filesystem is read-only", summary_de="Zielmedium ist nur lesbar gemountet.", summary_en="Target medium is mounted read-only.", severity="high", confidence="high", detection_sources=["file_check"], tags=["filesystem"]),
    DiagnosticCase(id="FS-FULL-022", domain="storage_filesystem", title_de="Zielmedium voll", title_en="Target medium full", summary_de="Freier Speicher ist zu gering fuer Aktion.", summary_en="Insufficient free disk space for operation.", severity="high", confidence="high", detection_sources=["file_check"], tags=["storage"]),
    DiagnosticCase(id="OWNER-MODE-023", domain="permissions", title_de="Owner/Mode unpassend", title_en="Wrong owner or mode", summary_de="Pfad existiert, aber Owner/Mode weicht vom Modell ab.", summary_en="Path exists but owner/mode does not match expected model.", severity="medium", confidence="high", detection_sources=["file_check"], tags=["permissions"]),
    DiagnosticCase(id="PI-BOOT-024", domain="hardware_raspberry_pi", title_de="Pi bootet nicht sauber", title_en="Pi does not boot cleanly", summary_de="Bootmedium erkannt, aber Startpfad bricht ab.", summary_en="Boot medium detected but boot path fails.", severity="high", confidence="medium", detection_sources=["log_pattern", "api_result"], tags=["raspberry_pi", "boot"]),
    DiagnosticCase(id="PI-NVME-025", domain="hardware_raspberry_pi", title_de="NVMe/USB-Bootkontext unstimmig", title_en="NVMe/USB boot context mismatch", summary_de="Boot-Konfiguration passt nicht zum gewaehlten Medium.", summary_en="Boot configuration does not match selected boot medium.", severity="medium", confidence="medium", detection_sources=["config_check"], tags=["nvme", "usb"]),
    DiagnosticCase(id="PI-CONFIG-026", domain="hardware_raspberry_pi", title_de="Noetige Konfigurationsdatei fehlt", title_en="Required config file missing", summary_de="Pi-spezifische Konfiguration ist nicht vorhanden.", summary_en="Pi-specific configuration file is missing.", severity="medium", confidence="high", detection_sources=["file_check"], tags=["config"]),
    DiagnosticCase(id="UPDATES-027", domain="updates_packages", title_de="Paketquellen oder Updates fehlschlagen", title_en="Package updates failing", summary_de="APT/Update-Lauf endet mit Fehlern.", summary_en="APT/update execution fails.", severity="low", confidence="medium", detection_sources=["api_result", "log_pattern"], tags=["apt"]),
    DiagnosticCase(id="DOCKER-028", domain="docker_container_runtime", title_de="Container-Runtime nicht betriebsbereit", title_en="Container runtime not operational", summary_de="Docker/Container-Dienst ist nicht verfuegbar.", summary_en="Docker/container service is unavailable.", severity="medium", confidence="medium", detection_sources=["systemctl", "api_result"], tags=["docker"]),
    DiagnosticCase(id="LOGS-029", domain="logs_runtime", title_de="Nur Symptom, Root-Cause unklar", title_en="Symptom detected, root cause unclear", summary_de="Es gibt Fehleranzeichen, aber keine harte Root-Cause-Evidenz.", summary_en="There are error symptoms but no hard root-cause evidence.", severity="low", confidence="low", detection_sources=["log_pattern"], tags=["symptom"]),
    DiagnosticCase(id="APP-030", domain="app_setuphelfer_runtime", title_de="Setuphelfer Runtime unstabil", title_en="Setuphelfer runtime unstable", summary_de="Mehrere Signale zeigen einen instabilen Laufzeitzustand.", summary_en="Multiple signals indicate unstable runtime state.", severity="medium", confidence="medium", detection_sources=["api_result", "systemctl", "log_pattern"], tags=["runtime"]),
    DiagnosticCase(id="SYSTEMD-NNP-031", domain="systemd_services", title_de="NoNewPrivileges blockiert sudo", title_en="NoNewPrivileges blocks sudo", summary_de="Der Runtime-Kontext verhindert sudo-Ausfuehrung durch gesetztes no_new_privileges.", summary_en="Runtime context blocks sudo execution due to no_new_privileges.", severity="critical", confidence="high", detection_sources=["api_result", "systemctl", "log_pattern"], root_causes=["Zu restriktive Service-Sandboxing-Optionen"], recommended_actions=[_a("review-systemd-sandbox", 1, "Systemd-Optionen wie NoNewPrivileges/Restriktionen pruefen und reproduzierbar korrigieren.", "Review and correct systemd sandbox options such as NoNewPrivileges.")], tags=["systemd", "sudo", "no_new_privileges"]),
    DiagnosticCase(id="STORAGE-PROTECTION-001", domain="storage_filesystem", title_de="Schreibzugriff: Systemplatte blockiert", title_en="Write blocked: system disk", summary_de="Das Ziel liegt auf der Systemplatte (/) — Schreibzugriffe sind nicht erlaubt.", summary_en="Target is on the system disk (/) — writes are not allowed.", severity="critical", confidence="high", detection_sources=["api_result", "storage_protection"], destructive_risk=True, root_causes=["Backup-Pfad auf Root-Dateisystem", "Falsches Laufwerk gewaehlt"], recommended_actions=[_a("use-safe-mount", 1, "Nur unter /mnt/setuphelfer/… oder freigegebenen Praefixen sichern.", "Use only /mnt/setuphelfer/… or configured safe prefixes.")], tags=["storage", "write_protection", "system_disk"]),
    DiagnosticCase(id="STORAGE-PROTECTION-002", domain="storage_filesystem", title_de="Schreibzugriff: Boot-Medium blockiert", title_en="Write blocked: boot disk", summary_de="Ziel enthaelt /boot oder EFI — Schreibzugriffe sind nicht erlaubt.", summary_en="Target involves /boot or EFI — writes are not allowed.", severity="critical", confidence="high", detection_sources=["api_result", "storage_protection"], destructive_risk=True, tags=["storage", "write_protection", "boot"]),
    DiagnosticCase(id="STORAGE-PROTECTION-003", domain="storage_filesystem", title_de="Schreibzugriff: Fremdes OS (Windows) blockiert", title_en="Write blocked: foreign OS (Windows)", summary_de="Windows-/NTFS-Heuristik oder EFI/Microsoft erkannt — Schreibzugriffe sind nicht erlaubt.", summary_en="Windows/NTFS heuristics or EFI/Microsoft detected — writes are not allowed.", severity="critical", confidence="medium", detection_sources=["api_result", "storage_protection"], destructive_risk=True, tags=["storage", "write_protection", "windows"]),
    DiagnosticCase(id="STORAGE-PROTECTION-004", domain="storage_filesystem", title_de="Schreibzugriff: Ziel nicht auf Allowlist", title_en="Write blocked: not allowlisted", summary_de="Pfad oder Blockgeraet entspricht nicht den freigegebenen Mustern.", summary_en="Path or block device does not match allowed patterns.", severity="critical", confidence="high", detection_sources=["api_result", "storage_protection"], tags=["storage", "write_protection", "allowlist"]),
    DiagnosticCase(id="STORAGE-PROTECTION-005", domain="storage_filesystem", title_de="Schreibzugriff: unsicherer Mount-Baum", title_en="Write blocked: unsafe mount tree", summary_de="Ziele unter /media oder /run/media sind fuer Schreibzugriffe nicht erlaubt.", summary_en="Targets under /media or /run/media are not allowed for writes.", severity="critical", confidence="high", detection_sources=["api_result", "storage_protection"], tags=["storage", "write_protection", "automount"]),
]


def get_catalog() -> list[DiagnosticCase]:
    return DIAGNOSTIC_CATALOG


def get_case_by_id(diagnosis_id: str) -> DiagnosticCase | None:
    for item in DIAGNOSTIC_CATALOG:
        if item.id == diagnosis_id:
            return item
    return None
